### ISSUE TITLE
wiki dataset not available on AWS link

### ISSUE THREAD

**Issue by madaanpulkit** [amzn/amazon-multi-token-completion#4]
## Description
The EMAT training example in `README.md` uses `matrix_plugin.py` which expects the downloaded data directory to have `input_data_bert-base-cased_wiki_pub` sub-directory with a `huggingface` dataset class serialized present. The AWS link doesn't house this.

```bash
> aws --no-sign-request --region=us-east-1 s3 ls s3://multi-token-completion/

                           PRE general_purpose/
                           PRE human_annotated/
                           PRE pubmed_frequent/
                           PRE pubmed_key_phrases/
2023-02-07 08:40:29       1137 README.txt

> aws --no-sign-request --region=us-east-1 s3 ls s3://multi-token-completion/general_purpose/

2023-02-07 08:41:59   66351505 dev.csv
2023-02-07 08:41:59   66166007 test.csv
2023-02-07 08:41:59 1193250188 train.csv
```

### 1. Loading `general_purpose` directly from `s3`
It isn't able to locate credentials, and I wasn't able to find a way to pass the required flags via `huggingface`

```bash
> python matrix_plugin.py --input_path s3://multi-token-completion/general_purpose/

....
botocore.exceptions.NoCredentialsError: Unable to locate credentials
```

### 2. Downloading and passing `general_purpose`
I then proceeded to download the dataset via `awscli` and tried passing the local path, but it expects the location to have a huggingface serialized dataset.

```bash
> python matrix_plugin.py --input_path /content/data/general_purpose

...
FileNotFoundError: Directory /content/data/general_purpose is neither a `Dataset` directory nor a `DatasetDict` directory.
```

### 3. Manipulating code to load `general_purpose/`
I tried loading the dataset as a CSV dataset 

Modification at [L237](https://github.com/amzn/amazon-multi-token-completion/blob/f277c0a88370e2aa96d1b6604d092c904bb2b0ab/matrix_plugin.py#L237)

```python
dataset = datasets.load_dataset('csv', data_dir=input_path)
```
I ran into another error. `def create_mapping` expects the data to have a column named `np` and `MatrixDecoder` expects `input_features` columns, both of which aren't present in any of the datasets uploaded.

### 4. Generating data from the scripts in `data/`
The data that the scripts create is in a different format than what the code expects. This one too is missing `input_features` column.

**Comment by orenkal** [comment]
Hi @madaanpulkit, thank you for raising the issue.
I updated the README and code to account for the required preprocessing step.
